// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Kq2zKkxa6UpF_1ydzOqaLoKQw-_21yg',
    appId: '1:25834670399:web:e2ca3ba4aa53960273ab8a',
    messagingSenderId: '25834670399',
    projectId: 'finalpaperpractice-810be',
    authDomain: 'finalpaperpractice-810be.firebaseapp.com',
    storageBucket: 'finalpaperpractice-810be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-yDDswHZo0av_Pq2ozzGrvUyobOvKS_I',
    appId: '1:25834670399:android:d0ed5c973a0886d373ab8a',
    messagingSenderId: '25834670399',
    projectId: 'finalpaperpractice-810be',
    storageBucket: 'finalpaperpractice-810be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMHrmDbDS7BAlzwAL24v3fOMMeqT5oNp4',
    appId: '1:25834670399:ios:8f5b0192f3690c2b73ab8a',
    messagingSenderId: '25834670399',
    projectId: 'finalpaperpractice-810be',
    storageBucket: 'finalpaperpractice-810be.appspot.com',
    iosBundleId: 'com.example.finalPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMHrmDbDS7BAlzwAL24v3fOMMeqT5oNp4',
    appId: '1:25834670399:ios:4a08f6bac45ae07f73ab8a',
    messagingSenderId: '25834670399',
    projectId: 'finalpaperpractice-810be',
    storageBucket: 'finalpaperpractice-810be.appspot.com',
    iosBundleId: 'com.example.finalPractice.RunnerTests',
  );
}
